//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IniTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IniTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically translate selected items using the configured API.
        /// </summary>
        public static string AutomaticallyTranslateSelectedItemsUsingTheConfiguredAPI {
            get {
                return ResourceManager.GetString("AutomaticallyTranslateSelectedItemsUsingTheConfiguredAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search.
        /// </summary>
        public static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the application.
        /// </summary>
        public static string CloseTheApplication {
            get {
                return ResourceManager.GetString("CloseTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from _English.
        /// </summary>
        public static string CopyFromEnglish {
            get {
                return ResourceManager.GetString("CopyFromEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected items to clipboard.
        /// </summary>
        public static string CopySelectedItemsToClipboard {
            get {
                return ResourceManager.GetString("CopySelectedItemsToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the translation for this key.
        /// </summary>
        public static string EditTheTranslationForThisKey {
            get {
                return ResourceManager.GetString("EditTheTranslationForThisKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Regular Expression search.
        /// </summary>
        public static string EnableRegularExpressionSearch {
            get {
                return ResourceManager.GetString("EnableRegularExpressionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _English INI.
        /// </summary>
        public static string EnglishINI {
            get {
                return ResourceManager.GetString("EnglishINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search within translations.
        /// </summary>
        public static string EnterTextToSearchWithinTranslations {
            get {
                return ResourceManager.GetString("EnterTextToSearchWithinTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extract from Game.
        /// </summary>
        public static string ExtractFromGame {
            get {
                return ResourceManager.GetString("ExtractFromGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract the English INI file from game files.
        /// </summary>
        public static string ExtractTheEnglishINIFileFromGameFiles {
            get {
                return ResourceManager.GetString("ExtractTheEnglishINIFileFromGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace text in selected translations.
        /// </summary>
        public static string FindAndReplaceTextInSelectedTranslations {
            get {
                return ResourceManager.GetString("FindAndReplaceTextInSelectedTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French (France).
        /// </summary>
        public static string FrenchFrance {
            get {
                return ResourceManager.GetString("FrenchFrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Germany).
        /// </summary>
        public static string GermanGermany {
            get {
                return ResourceManager.GetString("GermanGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Case.
        /// </summary>
        public static string IgnoreCase {
            get {
                return ResourceManager.GetString("IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore case during search.
        /// </summary>
        public static string IgnoreCaseDuringSearch {
            get {
                return ResourceManager.GetString("IgnoreCaseDuringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini Translator.
        /// </summary>
        public static string IniTranslator {
            get {
                return ResourceManager.GetString("IniTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian (Italy).
        /// </summary>
        public static string ItalianItaly {
            get {
                return ResourceManager.GetString("ItalianItaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to _Line....
        /// </summary>
        public static string JumpToLine {
            get {
                return ResourceManager.GetString("JumpToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Next Change.
        /// </summary>
        public static string JumpToNextChange {
            get {
                return ResourceManager.GetString("JumpToNextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about Ini Translator.
        /// </summary>
        public static string LearnMoreAboutIniTranslator {
            get {
                return ResourceManager.GetString("LearnMoreAboutIniTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: .
        /// </summary>
        public static string LineW {
            get {
                return ResourceManager.GetString("LineW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian (Lithuania).
        /// </summary>
        public static string LithuanianLithuania {
            get {
                return ResourceManager.GetString("LithuanianLithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load _Backup.
        /// </summary>
        public static string Load_Backup {
            get {
                return ResourceManager.GetString("Load_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Placeholders.
        /// </summary>
        public static string MissingPlaceholders {
            get {
                return ResourceManager.GetString("MissingPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are missing or mismatched placeholders in your translations. Please review and correct them before saving..
        /// </summary>
        public static string MissingPlaceholdersDesc {
            get {
                return ResourceManager.GetString("MissingPlaceholdersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to a specific line number in the list.
        /// </summary>
        public static string NavigateToASpecificLineNumberInTheList {
            get {
                return ResourceManager.GetString("NavigateToASpecificLineNumberInTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the next changed translation.
        /// </summary>
        public static string NavigateToTheNextChangedTranslation {
            get {
                return ResourceManager.GetString("NavigateToTheNextChangedTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the next translation with missing placeholders.
        /// </summary>
        public static string NavigateToTheNextTranslationWithMissingPlaceholders {
            get {
                return ResourceManager.GetString("NavigateToTheNextTranslationWithMissingPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Missing Placeholder.
        /// </summary>
        public static string NextMissingPlaceholder {
            get {
                return ResourceManager.GetString("NextMissingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Old INI File....
        /// </summary>
        public static string Open_OldINIFile {
            get {
                return ResourceManager.GetString("Open_OldINIFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an older version of the INI file for comparison.
        /// </summary>
        public static string OpenAnOlderVersionOfTheINIFileForComparison {
            get {
                return ResourceManager.GetString("OpenAnOlderVersionOfTheINIFileForComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open English and Translated INI files.
        /// </summary>
        public static string OpenEnglishAndTranslatedINIFiles {
            get {
                return ResourceManager.GetString("OpenEnglishAndTranslatedINIFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the English INI file location in Explorer.
        /// </summary>
        public static string OpenTheEnglishINIFileLocationInExplorer {
            get {
                return ResourceManager.GetString("OpenTheEnglishINIFileLocationInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the settings window to configure preferences.
        /// </summary>
        public static string OpenTheSettingsWindowToConfigurePreferences {
            get {
                return ResourceManager.GetString("OpenTheSettingsWindowToConfigurePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Translated INI file location in Explorer.
        /// </summary>
        public static string OpenTheTranslatedINIFileLocationInExplorer {
            get {
                return ResourceManager.GetString("OpenTheTranslatedINIFileLocationInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste clipboard contents into selected items.
        /// </summary>
        public static string PasteClipboard {
            get {
                return ResourceManager.GetString("PasteClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a version from the list:.
        /// </summary>
        public static string PleaseSelectAVersionFromTheList {
            get {
                return ResourceManager.GetString("PleaseSelectAVersionFromTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        public static string PortugueseBrazil {
            get {
                return ResourceManager.GetString("PortugueseBrazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload translations from the INI files.
        /// </summary>
        public static string ReloadTranslationsFromTheINIFiles {
            get {
                return ResourceManager.GetString("ReloadTranslationsFromTheINIFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Text.
        /// </summary>
        public static string ReplaceText {
            get {
                return ResourceManager.GetString("ReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace translations with their English counterparts.
        /// </summary>
        public static string ReplaceTranslationsWithTheirEnglishCounterparts {
            get {
                return ResourceManager.GetString("ReplaceTranslationsWithTheirEnglishCounterparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace With:.
        /// </summary>
        public static string ReplaceWith {
            get {
                return ResourceManager.GetString("ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore translations from a backup file.
        /// </summary>
        public static string RestoreTranslationsFromABackupFile {
            get {
                return ResourceManager.GetString("RestoreTranslationsFromABackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your current translations.
        /// </summary>
        public static string SaveYourCurrentTranslations {
            get {
                return ResourceManager.GetString("SaveYourCurrentTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text:.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Version.
        /// </summary>
        public static string SelectVersion {
            get {
                return ResourceManager.GetString("SelectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsViewModel_Dark {
            get {
                return ResourceManager.GetString("SettingsViewModel_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsViewModel_Light {
            get {
                return ResourceManager.GetString("SettingsViewModel_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepL Api Key:.
        /// </summary>
        public static string SettingsWindow_DeepLApiKey {
            get {
                return ResourceManager.GetString("SettingsWindow_DeepLApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate Api Key:.
        /// </summary>
        public static string SettingsWindow_GoogleTranslateApiKey {
            get {
                return ResourceManager.GetString("SettingsWindow_GoogleTranslateApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsWindow_Language {
            get {
                return ResourceManager.GetString("SettingsWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Settings {
            get {
                return ResourceManager.GetString("SettingsWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string SettingsWindow_Theme {
            get {
                return ResourceManager.GetString("SettingsWindow_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Provider:.
        /// </summary>
        public static string SettingsWindow_TranslationProvider {
            get {
                return ResourceManager.GetString("SettingsWindow_TranslationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Spain).
        /// </summary>
        public static string SpanishSpain {
            get {
                return ResourceManager.GetString("SpanishSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarCitizen Path:.
        /// </summary>
        public static string StarCitizenPath {
            get {
                return ResourceManager.GetString("StarCitizenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Theme.
        /// </summary>
        public static string SwitchTheme {
            get {
                return ResourceManager.GetString("SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Dark theme.
        /// </summary>
        public static string SwitchToDarkTheme {
            get {
                return ResourceManager.GetString("SwitchToDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Light theme.
        /// </summary>
        public static string SwitchToLightTheme {
            get {
                return ResourceManager.GetString("SwitchToLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle between Light and Dark themes.
        /// </summary>
        public static string ToggleBetweenLightAndDarkThemes {
            get {
                return ResourceManager.GetString("ToggleBetweenLightAndDarkThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Keys:.
        /// </summary>
        public static string TotalKeys {
            get {
                return ResourceManager.GetString("TotalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Translated INI.
        /// </summary>
        public static string TranslatedINI {
            get {
                return ResourceManager.GetString("TranslatedINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View detailed documentation and usage instructions.
        /// </summary>
        public static string ViewDetailedDocumentationAndUsageInstructions {
            get {
                return ResourceManager.GetString("ViewDetailedDocumentationAndUsageInstructions", resourceCulture);
            }
        }
    }
}
